DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS pictures;
DROP TABLE IF EXISTS specials;

CREATE TABLE users (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR NOT NULL,
  email VARCHAR NOT NULL UNIQUE,
  password_digest VARCHAR NOT NULL,
  token VARCHAR NOT NULL
);

CREATE TABLE pictures (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255),
  url VARCHAR(225) NOT NULL,
  description VARCHAR(255)
);

CREATE TABLE specials (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255),
  description VARCHAR(255) NOT NULL,
  start_date TIMESTAMP NOT NULL,
  end_date TIMESTAMP NOT NULL
);
